# Generated by Django 3.0.7 on 2020-09-14 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/post')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('post_date', models.DateTimeField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=255)),
                ('description', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
